//
// Created by RedRa on 29.05.2021.
//

#ifndef ICC_SRC_ICC__PRIVATE_DYNAMIC_LIB_API_TRIGGER_HPP_
#define ICC_SRC_ICC__PRIVATE_DYNAMIC_LIB_API_TRIGGER_HPP_

#define ICC_SHARED_LIBRARY

#endif //ICC_SRC_ICC__PRIVATE_DYNAMIC_LIB_API_TRIGGER_HPP_
